=== 18965050/EasyValidator/src/test/resources/validator/entity.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2013 (http://www.altova.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="entity">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="fields" />
        <xs:element ref="groups" />
      </xs:sequence>
      <xs:attribute name="class" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
  <xs:element name="valid">
    <xs:complexType>
      <xs:attribute name="alias" type="xs:string" use="optional" />
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="msg" type="xs:string" use="required" />
      <xs:attribute name="min" type="xs:string" use="optional" />
      <xs:attribute name="max" type="xs:string" use="optional" />
      <xs:attribute name="url" type="xs:string" use="optional" />
      <xs:attribute name="regex" type="xs:string" use="optional" />
      <xs:attribute name="restrict" type="xs:string" use="optional" />
      <xs:attribute name="flag" type="xs:string" use="optional" />
      <xs:attribute name="ref" type="xs:string" use="optional" />
      <!--<xs:any namespace='http://www.w3.org/1999/xhtml' minOccurs='0' maxOccurs='unbounded' processContents='lax' />-->
    </xs:complexType>
  </xs:element>
  <xs:element name="groups">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="group" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="group">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="field" minOccurs="0" />
        <xs:element ref="script" minOccurs="0" />
        <xs:any namespace='http://www.w3.org/1999/xhtml' minOccurs='0' maxOccurs='unbounded' processContents='lax' />
      </xs:choice>
      <xs:attribute name="name" type="xs:string" use="required" />
      <xs:attribute name="extends" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>
  <xs:element name="fields">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="field" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="field">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="valid" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
      <xs:attribute name="property" type="xs:string" use="required" />
      <xs:attribute name="valid-alias" type="xs:string" use="optional" />
    </xs:complexType>
  </xs:element>
  <xs:element name="script">
    <xs:complexType>
      <xs:choice minOccurs="1" maxOccurs="unbounded">
        <xs:element ref="field" minOccurs="0" />
        <xs:element ref="script" minOccurs="0" />
        <xs:any namespace='http://www.w3.org/1999/xhtml' minOccurs='0' maxOccurs='unbounded' processContents='lax' />
      </xs:choice>
      <xs:attribute name="test" type="xs:string" use="required" />
    </xs:complexType>
  </xs:element>
</xs:schema>

=== 18965050/EasyValidator/src/test/resources/validator/ValidSample.entity.xml
<?xml version="1.0" encoding="UTF-8"?>
<entity class="cn.xyz.chaos.validator.test.entity.ValidSample" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="entity.xsd">
  <fields>
    <field property="name"  valid-alias="require,regex,length">
      <valid name="required" msg="name should required" />
      <valid name="notnull" msg="name should not null" />
      <valid name="notblank" msg="name should not blank" />
      <valid name="regex" regex="\w+" msg="name regex{a-z,1-9,_}" />
      <valid name="length" min="2" max="4" msg="name length from 2 to 4"/>
      <valid name="size" min="2" max="4" msg="name length from 2 to 4"/>
    </field>
    <field property="gender" valid-alias="restrict">
      <valid name="restrict" restrict="0,1" msg="gender should 男/女（0/1）"/>
      <valid name="min" min="0" msg="age min is 0"/>
      <valid name="max" max="1" msg="age max is 1" />
    </field>
    <field property="age">
      <valid name="min" min="0" msg="age min is 0"/>
      <valid name="max" max="99" msg="age max is 99" />

      <valid name="range" min="0" max="99" msg="age range from 0 to 99" />
    </field>
    <field property="birthday" valid-alias="past">
      <valid name="past" msg="birthday should past"/>
      <valid name="future" msg="birthday should not future"/>
    </field>
    <field property="idcard">
      <valid name="idcard"  msg="idcard should idcard"/>
      <valid name="atmost" ref="age,birthday,idcard" max="2" msg="age|birthday|idcard至多填写两个" />
      <valid name="atleast" ref="age,birthday,idcard" min="1" msg="age|birthday|idcard至少填写一个" />
    </field>
    <field property="nick" valid-alias="null,equal">
      <valid name="null" msg="nick不能为NULL" />
      <valid name="equal" ref="name,nick" msg="nick必须与name相同" />
      <valid name="compare" ref="name,nick" flag="EQ" msg="nick必须与name相同" />
    </field>
    <field property="url">
      <valid name="url" msg="url should xyz"/>
      <valid name="url" url="http://x.y.z:80" msg="url should xyz"/>
    </field>
    <field property="email">
      <valid name="email"  msg="email必须邮件格式"/>
    </field>
  </fields>
  <groups>
    <group name="submit">
      <field property="name" />
      <field property="gender" />
      <field property="age" />
      <field property="birthday" />
      <field property="idcard" />
      <field property="nick" />
      <field property="url" />
      <field property="email" />
    </group>
    <group name="submit1">
      <field property="name" valid-alias="notnull,notblank,regex,size" />
      <field property="gender" valid-alias="min,max" />
    </group>
  </groups>
</entity>

=== 18965050/EasyValidator/src/test/resources/validator/Sample.entity.xml
<?xml version="1.0" encoding="UTF-8"?>
<entity class="cn.xyz.chaos.validator.test.entity.SampleDTO" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="entity.xsd">
    <fields>
        <field property="int1">
            <valid name="min" min="1" msg="int1最小为1"/>
            <valid name="max" max="11" msg="int1最大为11"/>
        </field>
        <field property="int2">
            <valid name="min" min="2" msg="int2最小为2"/>
            <valid name="max" max="11" msg="int2最大为12"/>
        </field>
        <field property="int3">
            <valid name="min" min="3" msg="int3最小为3"/>
            <valid name="max" max="11" msg="int3最大为13"/>
        </field>
    </fields>
    <groups>
        <group name="test_int_min_max">
            <field property="int1"/>
            <field property="int2"/>
            <field property="int3"/>
        </group>
    </groups>
</entity>

=== 18965050/EasyValidator/src/test/resources/validator/UserDTO.entity.xml
<?xml version="1.0" encoding="UTF-8"?>
<entity class="cn.xyz.chaos.validator.test.entity.UserDTO" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="entity.xsd">
  <fields>
    <field property="logUsername">
      <valid name="required" msg="用户名不能为空" />
      <valid name="length" min="4" max="8" msg="用户名长度为4-8个字符" />
      <valid name="regex" regex="\w+" msg="用户名为字符a-z,1-9,_" />
    </field>
    <field property="logPassword" valid-alias="required,length">
      <valid name="required" msg="密码不能为空" />
      <valid name="length" min="4" max="8" msg="密码长度为4-8个字符" />
      <valid name="regex" regex="\w+" msg="密码为字符a-z,1-9" />
    </field>
    <field property="logPassword2">
      <valid name="required" msg="密码不能为空" />
      <valid name="equal" ref="logPassword,logPassword2" msg="两次输入不一致" />
    </field>
    <field property="name">
      <valid name="required" msg="姓名不能为空" />
      <valid name="regex" regex="[\u4e00-\u9fbb]+" msg="姓名必须是汉字" />
      <valid name="length" min="2" max="4" msg="姓名长度为2-4个字符" />
    </field>
    <field property="gender" valid-alias="required,range">
      <valid name="required" msg="性别不能为空" />
      <valid name="range" min="0" max="1" msg="性别格式错误" />
      <valid name="min" min="0" msg="性别不能小于0" />
      <valid name="max" max="1" msg="性别不能大于1" />
      <valid name="restrict" restrict="0,1" msg="性别只能取0或1" />
    </field>
    <field property="mobile">
      <valid name="regex" regex="\d{11}" msg="手机号码格式错误" />
    </field>
    <field property="phone">
      <valid name="regex" regex="\d+" msg="电话号码格式错误" />
      <valid name="atleast" min="1" ref="mobile,phone" msg="手机、电话至少填写一个" />
    </field>
  </fields>
  <groups>
    <group name="login">
      <field property="logUsername" />
      <field property="logPassword" />
    </group>
    <group name="regist">
      <field property="logUsername" />
      <field property="logPassword" />
      <field property="logPassword2" />
      <field property="name" />
      <field property="gender" />
      <field property="mobile" />
      <field property="phone" />
    </group>
    <group name="regist1">
      <field property="logUsername" />
      <field property="logPassword" />
      <field property="logPassword2" />
      <field property="name" />
      <field property="gender" valid-alias="required,min,max" />
      <field property="mobile" />
      <field property="phone" />
    </group>
    <group name="regist2">
      <field property="logUsername" />
      <field property="logPassword" />
      <field property="logPassword2" />
      <field property="name" />
      <field property="gender" valid-alias="required,restrict" />
      <field property="mobile" />
      <field property="phone" />
    </group>
    <group name="registSimple">
      <field property="logUsername" valid-alias="required,length" />
      <field property="logPassword" />
      <field property="logPassword2" />
    </group>
    <group name="registScript">
      <field property="logUsername" />
      <field property="logPassword" />
      <field property="logPassword2" />
      <field property="name" />
	  <!-- 如果是gender==0，姓名、手机|电话必填-->
      <script test="target.gender==0">
		<field property="mobile" />
		<field property="phone" />
      </script>
    </group>
  </groups>
</entity>
